## 02 scikit-learn 中的 kNN 

使用函数将算法封装 如下

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.093607318, 3.365731514]) #将要预测的x

In [4]:
%run kNN_function/kNN.py #魔法命令

In [5]:
predict_y = kNN_classify(6, X_train, y_train, x)

In [6]:
predict_y

1

### 使用scikit-learn中的kNN

In [7]:
from sklearn.neighbors import KNeighborsClassifier #以面向对象形式包装了kNN算法

In [8]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6) #创建实例 传入k值

In [9]:
kNN_classifier.fit(X_train, y_train) #拟合 传入训练集矩阵X 标签向量y 返回值是该对象自身

KNeighborsClassifier(n_neighbors=6)

In [14]:
kNN_classifier.predict(x) #报错 需要传入矩阵 每一行是要预测的样本 而x只是一个向量

ValueError: Expected 2D array, got 1D array instead:
array=[8.09360732 3.36573151].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [15]:
X_predict = x.reshape(1, -1) #把x reshape成矩阵 一个元素 -1：自动决定第二个维度有多少

In [16]:
X_predict

array([[8.09360732, 3.36573151]])

In [17]:
kNN_classifier.predict(X_predict)

array([1])

In [18]:
y_predict = kNN_classifier.predict(X_predict) #结果是一个向量 只有一个元素

In [19]:
y_predict[0]

1

### 重新整理我们的kNN的代码

代码参见 [这里](kNN/KNN.py)

In [20]:
%run kNN/kNN.py #魔法命令

In [21]:
knn_clf = KNNClassifier(3)

In [22]:
knn_clf.fit(X_train, y_train) #先训练

KNN(k=3)

In [23]:
y_predict = knn_clf.predict(X_predict) #预测

In [24]:
y_predict

array([1])

In [26]:
y_predict[0]

1

sklearn内部kNN比这复杂 因为kNN本身预测很耗时