# 06 numpy.array合并和分割

In [1]:
import numpy as np

## numpy.array的合并

In [9]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [3]:
x

array([1, 2, 3])

In [6]:
y

array([3, 2, 1])

In [7]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [11]:
z = np.array([666, 666, 666])

In [12]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [14]:
A = np.array([[1,2,3],
             [4,5,6]])

In [15]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [16]:
np.concatenate([A,A], axis=1) #沿第二个维度的方向进行拼接（默认是0）

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [17]:
np.concatenate([A,z]) #concatenate只能拼接维度相同的元素

ValueError: all the input arrays must have same number of dimensions

In [18]:
np.concatenate([A, z.reshape(1,-1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [19]:
A 

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
A2=np.concatenate([A, z.reshape(1,-1)])

In [21]:
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [23]:
np.vstack([A, z]) #垂直方向相叠 更智能 容忍维度不同

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [27]:
B=np.full((2,2),100)
B

array([[100, 100],
       [100, 100]])

In [28]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [29]:
np.hstack([A,z]) #A:2*3 z:1*3 无法水平堆叠

ValueError: all the input arrays must have same number of dimensions

## numpy.array的分割操作

In [30]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x1, x2, x3 = np.split(x, [3,7]) #[0,3) [3,7) [7,end)

In [32]:
x1

array([0, 1, 2])

In [33]:
x2

array([3, 4, 5, 6])

In [34]:
x3

array([7, 8, 9])

In [35]:
x1, x2 = np.split(x, [5])

In [36]:
x1

array([0, 1, 2, 3, 4])

In [37]:
x2

array([5, 6, 7, 8, 9])

In [40]:
A=np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
A1, A2 = np.split(A,[2])

In [42]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [43]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
A1, A2 = np.split(A, [2], axis=1)

In [46]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [47]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [48]:
upper ,lower = np.vsplit(A, [2])

In [49]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [50]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
left, right = np.hsplit(A,[2])

In [52]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [53]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [54]:
data = np.arange(16).reshape((4,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
x, y=np.hsplit(data,[-1]) #最后一列拿下来

In [56]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [57]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [58]:
y[:,0] #变成一个向量 每一行的全部 第0列

array([ 3,  7, 11, 15])