# numpy.array 中的运算

给定一个向量，让向量中每一个数乘以2

a = (0, 1, 2)

a\*2 = (0, 2, 4)

In [1]:
n=10
L=[i for i in range(n)]

In [2]:
2*L #将两个L首尾相接 不是每个元素乘2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
A=[]
for i in L:
    A.append(2*i)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [2]:
n=1000000
L=[i for i in range(n)]

In [3]:
%%time
A=[]
for i in L:
    A.append(2*i)

Wall time: 215 ms


In [4]:
%%time
A = [2*i for i in L] #生成表达式远快于for循环

Wall time: 248 ms


In [5]:
import numpy as np
L=np.arange(n)

In [6]:
%%time
A=np.array(2*i for i in L)

Wall time: 25.9 ms


In [7]:
%%time
A=2*L #numpy array 这样就表示每个元素乘2

Wall time: 4.99 ms


In [10]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [11]:
n=10
L=np.arange(n)
2*L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## NumPy's UFuncs (Universal Functions)

对向量、矩阵中的所有元素都执行的运算

In [13]:
X=np.arange(1,16).reshape((3,5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
X+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [15]:
X-1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
X*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [17]:
X/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [18]:
X//2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [19]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [20]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [21]:
1 / X #对矩阵中所有元素取倒数

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [22]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [23]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [24]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [25]:
np.tan(X) #还有相应的反三角函数

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [26]:
np.exp(X) #e^X

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [27]:
np.power(3, X) #3^X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [28]:
3**X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [29]:
np.log(X) #以e为底 自然对数

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [30]:
np.log2(X) #以2为底

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [31]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

## 矩阵运算

In [32]:
A=np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [34]:
B=np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [35]:
A+B

array([[10, 11],
       [12, 13]])

In [36]:
A-B

array([[-10,  -9],
       [ -8,  -7]])

In [37]:
A * B #对应元素相乘 numpy中所有运算符都是对每个元素

array([[ 0, 10],
       [20, 30]])

In [38]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [39]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [40]:
A

array([[0, 1],
       [2, 3]])

In [41]:
A.T #转置

array([[0, 2],
       [1, 3]])

In [ ]:
C = np.full((3,3),10) #矩阵乘法对矩阵形状有要求C3*3不能与A2*2相乘

In [42]:
A.dot(C)

NameError: name 'C' is not defined

## 向量和矩阵的运算

### 加法

In [55]:
v = np.array([1,2])

In [45]:
A

array([[0, 1],
       [2, 3]])

In [46]:
v + A #数学上向量和矩阵无法相加 但是在numpy里 相当于该向量与矩阵的每一行相加

array([[1, 3],
       [3, 5]])

In [48]:
np.vstack([v]*A.shape[0]) #将v向量叠起来有A的行数那么高 (居然是方括号...)

array([[1, 2],
       [1, 2]])

In [49]:
np.vstack([v]*A.shape[0])+A

array([[1, 3],
       [3, 5]])

In [50]:
np.tile(v,(2,1)) #行方向上堆叠两次  列方向上堆叠一次 相当于上面vstack那句话的效果

array([[1, 2],
       [1, 2]])

In [51]:
np.tile(v,(2,1))+A

array([[1, 3],
       [3, 5]])

### 乘法

In [52]:
v

array([1, 2])

In [53]:
A

array([[0, 1],
       [2, 3]])

In [54]:
v*A #A的每行的每个元素 乘 v的一个元素

array([[0, 2],
       [2, 6]])

In [56]:
v.dot(A)

array([4, 7])

In [57]:
A.dot(v) #v在这里被看成2*1的列向量

array([2, 8])

### 矩阵的逆

In [58]:
A

array([[0, 1],
       [2, 3]])

In [59]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [60]:
invA = np.linalg.inv(A)

In [62]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [63]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [65]:
X = np.arange(16).reshape((2,8))

In [66]:
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [68]:
np.linalg.inv(X) #2*8的矩阵 不能求逆矩阵

LinAlgError: Last 2 dimensions of the array must be square

### 矩阵的伪逆

In [69]:
pinvX=np.linalg.pinv(X) #伪逆阵
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -7.30583920e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [70]:
pinvX.shape

(8, 2)

In [71]:
X.dot(pinvX) #副对角线不完全是0 这是计算机的浮点误差造成的

array([[ 1.00000000e+00, -2.77555756e-16],
       [ 1.69309011e-15,  1.00000000e+00]])

逆矩阵 和原矩阵 不管是左乘还是右乘 得到的都是单位矩阵 所以只有方阵才有逆矩阵

对于非方阵 只能求伪逆矩阵 原矩阵乘伪逆矩阵 得到单位矩阵（方阵）

矩阵的伪逆又被称为“广义逆矩阵”，有兴趣可以翻看线性教材课本查看更多广义逆矩阵相关的性质。中文wiki链接: https://zh.wikipedia.org/wiki/%E5%B9%BF%E4%B9%89%E9%80%86%E9%98%B5