## 09 ``Numpy`` 中arg运算

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, 1000000)

### 索引

In [5]:
np.min(x)

-5.082280703240497

In [6]:
np.argmin(x) #最小值的索引

366766

In [7]:
x[366766]

-5.082280703240497

In [8]:
np.argmax(x)

28560

In [9]:
x[28560]

4.921996130658124

In [10]:
np.max(x)

4.921996130658124

### 排序和使用索引

In [11]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
np.random.shuffle(x)
x

array([ 0,  6,  3,  8,  9, 13,  4, 12, 14, 11, 10,  1,  5,  2,  7, 15])

In [13]:
np.sort(x) #返回一个对x排好序的向量（x本身还是乱序）

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
x

array([ 0,  6,  3,  8,  9, 13,  4, 12, 14, 11, 10,  1,  5,  2,  7, 15])

In [15]:
x.sort() #通过对象调用 对x本身排序

In [16]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
X = np.random.randint(10, size=(4,4))
X

array([[8, 3, 6, 0],
       [8, 2, 8, 4],
       [1, 1, 7, 2],
       [0, 5, 9, 2]])

In [19]:
np.sort(X) #对每行排序 axis默认值是1 

array([[0, 3, 6, 8],
       [2, 4, 8, 8],
       [1, 1, 2, 7],
       [0, 2, 5, 9]])

In [20]:
np.sort(X, axis=1) #沿着列的方向排序 每行都有序

array([[0, 3, 6, 8],
       [2, 4, 8, 8],
       [1, 1, 2, 7],
       [0, 2, 5, 9]])

In [21]:
np.sort(X, axis=0) #沿着行的方向排序 每列都有序

array([[0, 1, 6, 0],
       [1, 2, 7, 2],
       [8, 3, 8, 2],
       [8, 5, 9, 4]])

#### 使用索引

In [23]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
np.random.shuffle(x)

In [25]:
x

array([ 0,  3, 13, 11, 10,  2,  1, 15, 14,  4, 12,  8,  5,  7,  9,  6])

In [26]:
np.argsort(x) #索引排序

array([ 0,  6,  5,  1,  9, 12, 15, 13, 11, 14,  4,  3, 10,  2,  8,  7],
      dtype=int64)

快排 partition 随机取一个pivot 小于pivot的值都在它左边 大于pivot的值都在它右边

In [27]:
np.partition(x, 3) #3前面的数都比3小(不一定有序) 3后面的数都比3大（不一定有序）

array([ 0,  1,  2,  3,  4,  5,  6, 10, 14, 11, 12,  8, 13,  7,  9, 15])

有时只要找到比某个数小的或者比某个数大的数 只要先partition 再切片处理即可

In [29]:
np.argpartition(x, 3) #3的索引是1

array([ 0,  6,  5,  1,  9, 12, 15,  4,  8,  3, 10, 11,  2, 13, 14,  7],
      dtype=int64)

In [30]:
X

array([[8, 3, 6, 0],
       [8, 2, 8, 4],
       [1, 1, 7, 2],
       [0, 5, 9, 2]])

In [31]:
np.argsort(X, axis=1) #按行排序 返回索引

array([[3, 1, 2, 0],
       [1, 3, 0, 2],
       [0, 1, 3, 2],
       [0, 3, 1, 2]], dtype=int64)

In [32]:
np.argpartition(X, 2, axis=1) #以2为pivot

array([[3, 1, 2, 0],
       [1, 3, 2, 0],
       [0, 1, 3, 2],
       [0, 3, 1, 2]], dtype=int64)