## 03 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets #使用sklearn提供的数据集

In [2]:
iris = datasets.load_iris() #鸢尾花数据集
iris.keys() 

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
X = iris.data

In [4]:
y = iris.target

In [5]:
X.shape

(150, 4)

In [6]:
y.shape

(150,)

### train_test_split

分离出一部分数据做训练，另外一部分数据做测试。

In [7]:
y #并不能 X[:120]简单地将前120个元素当训练集

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
shuffled_indexes = np.random.permutation(len(X)) #打乱索引
shuffled_indexes

array([  6,  31,  90, 109,  92,  34,  77,  59,  55,  66, 137,  20, 139,
        30,  24, 126,  40, 104,  18,  57,  56,   7, 146,  10,  11, 124,
        83,  14,  32,  99,  74, 134,  72,  80,   3, 112,  22,  33,  84,
        91,  63,  95,  96,  93, 138,   2, 125, 114,   9,  76, 118, 108,
        19,  45,  23,  51,  27, 106, 132,  58, 110,  89, 135,  98,  44,
       103,  85, 142, 131, 136,  17,  64,  25,  29, 117,  38,  81, 111,
        46, 101,  97, 122, 129, 127,  75,  54,  16,  28, 115,  37, 133,
       120,  35,  94, 121, 145,  12, 130,  49,  65,  71,  26,  53,  87,
       128,  43, 116,   4,  47, 123,   8, 148,   5, 144,  67, 141,   1,
       119,  73,  70,  62,  68,  42,  86, 143,  82, 107,  79,  13,  88,
        15, 102, 149,  78, 140,  69,  50, 100,  39,  52,  48, 113,  61,
        60,   0,  36, 105, 147,  41,  21])

In [9]:
test_ratio = 0.2 #测试集比例
test_size = int(len(X) * test_ratio) #测试集数量 = X样本数 * 测试集比例

In [10]:
test_size

30

In [11]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]
#前30是测试集 后面是训练集

In [12]:
#Fancy Indexing
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [13]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [14]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 封装

In [15]:
from playML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [29]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [30]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 测试我们的算法

In [27]:
from playML.kNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [28]:
y_predict

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2])

In [31]:
y_test

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2])

In [32]:
sum(y_predict == y_test)

30

In [33]:
sum(y_predict == y_test) / len(y_test)

1.0

#### sklearn中的train_test_split

In [34]:
from sklearn.model_selection import train_test_split

train_test_split

<function sklearn.model_selection._split.train_test_split(*arrays, **options)>

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [36]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [37]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
