## 03 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets #使用sklearn提供的数据集

In [2]:
iris = datasets.load_iris() #鸢尾花数据集
iris.keys() 

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
X = iris.data

In [4]:
y = iris.target

In [5]:
X.shape

(150, 4)

In [6]:
y.shape

(150,)

### train_test_split

分离出一部分数据做训练，另外一部分数据做测试。

In [8]:
y #并不能 X[:120]简单地将前120个元素当训练集

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
shuffled_indexes = np.random.permutation(len(X)) #打乱索引
shuffled_indexes

array([143,  96,  34, 123, 147,  46,  71,   5, 135,  18, 148, 118, 103,
        57,  49,  90,  43, 101, 124,  23,  30,   2, 127,   6, 130, 149,
        37, 146,  61, 105, 117,   8, 104,  11,  12,  56,  33, 144,  74,
       142,  69,  44, 126,  92,  47, 113,  72,  48, 115,  85,  73,   9,
        80,  41, 108,  76,  66, 137,  15, 134, 110,  83,  29, 139,  94,
        75,  98,  81, 119, 106,  19,  82, 116,  45,  93,  68,  95, 109,
       102,   3,  63,  16, 100,  97, 132,  64,  77,  70,  21,  17,  52,
        38,  78,  62, 122,  88,   4,  84,  27,  36, 131, 111,   7,  14,
        20,  99, 141, 120,  86, 133,  28,  79,  55, 128, 136, 140,  54,
        25,  87,  60,  53, 145, 138,  50,  58, 121,  67,  32, 125,  10,
       107, 112,  22,  89,  35, 114,  42, 129,  59,  91,   0,  26,  65,
         1,  31,  13,  39,  24,  51,  40])

In [10]:
test_ratio = 0.2 #测试集比例
test_size = int(len(X) * test_ratio) #测试集数量 = X样本数 * 测试集比例

In [12]:
test_size

30

In [14]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]
#前30是测试集 后面是训练集

In [15]:
#Fancy Indexing
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [75]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [76]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 封装

In [83]:
from playML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [84]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [85]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 测试我们的算法

In [86]:
from playML.kNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [87]:
y_predict

array([2, 1, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 2, 2, 0, 1, 2, 1, 1, 0, 1, 0,
       1, 1, 2, 2, 0, 0, 1])

In [88]:
y_test

array([2, 1, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 2, 2, 0, 1, 2, 1, 1, 0, 1, 0,
       1, 1, 2, 2, 0, 0, 1])

In [90]:
sum(y_predict == y_test)

29

In [91]:
sum(y_predict == y_test) / len(y_test)

0.96666666666666667

#### sklearn中的train_test_split

In [92]:
from sklearn.model_selection import train_test_split

train_test_split

<function sklearn.model_selection._split.train_test_split>

In [93]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [94]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [95]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
