# 03 numpy.array 基础

In [1]:
import numpy

In [2]:
numpy.__version__

'1.16.0'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.16.0'

## Python List 的特点

为什么要使用numpy? Python List的缺点在哪？

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L[5]

5

In [7]:
L[5]=100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

Python List对类型不作限定，每个元素的类型都可以不一样

In [8]:
L[5]="sky"
L

[0, 1, 2, 3, 4, 'sky', 6, 7, 8, 9]

灵活但效率低

Python中也有限定一种类型的数组 array

## Python array 的特点

In [9]:
import array
arr = array.array('i', [i for i in range(10)]) # 第1个参数'i'表示整型
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[5]

5

In [11]:
arr[5]=100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [12]:
arr[5]='sky'

TypeError: an integer is required (got type str)

单一类型 效率高了，但是array没有向量相关的运算

## numpy.array

In [13]:
nparr=np.array([i for i in range(10)]) #只需要传一个参数 列表初始化
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
nparr[5]

5

In [15]:
nparr[5]=100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [16]:
nparr[5]='sky'

ValueError: invalid literal for int() with base 10: 'sky'

In [17]:
nparr.dtype #nparr是哪种类型

dtype('int32')

In [18]:
nparr[5]=5.0 #隐式类型转换

In [19]:
nparr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
nparr[3]=3.14 #传浮点数给整型 自动截位
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
nparr.dtype

dtype('int32')

In [24]:
nparr2 = np.array([1, 2, 3.0])
nparr2.dtype

dtype('float64')