## 08 ``Numpy`` 中的聚合操作

### sum

In [1]:
import numpy as np

L = np.random.random(100) #100个[0,1)之间的随机数
L

array([0.88225786, 0.11925392, 0.26126804, 0.60154474, 0.15936564,
       0.02717235, 0.50490766, 0.34943448, 0.66419966, 0.2702395 ,
       0.46068284, 0.50323504, 0.37888364, 0.40305906, 0.36648175,
       0.64567622, 0.03568831, 0.49308084, 0.21073254, 0.11584024,
       0.03448387, 0.45550341, 0.57794338, 0.31994728, 0.15684962,
       0.80031409, 0.55488673, 0.19757319, 0.68843242, 0.2101267 ,
       0.28485316, 0.14094056, 0.40296667, 0.72645312, 0.01669886,
       0.89494589, 0.25469687, 0.78279445, 0.27564242, 0.91636741,
       0.15277744, 0.95340301, 0.3294113 , 0.47467459, 0.65830057,
       0.82152588, 0.7859009 , 0.61897441, 0.13253028, 0.25717352,
       0.5453966 , 0.19447496, 0.78212573, 0.77022274, 0.78803078,
       0.90509203, 0.4229733 , 0.80530447, 0.9294152 , 0.66724494,
       0.2459771 , 0.8143497 , 0.73699433, 0.18457581, 0.02141947,
       0.13354135, 0.3424524 , 0.64137241, 0.60732128, 0.54524113,
       0.56290905, 0.1757311 , 0.06578523, 0.32415417, 0.47739

In [3]:
sum(L) #python中自带的sum 计算List列表的和

46.09889490020595

In [2]:
np.sum(L) #numpy中的sum

46.09889490020595

numpy效率高！

In [6]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

193 ms ± 40.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.83 ms ± 96.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### min, max

In [7]:
np.min(big_array)

2.762554560664654e-07

In [8]:
np.max(big_array)

0.9999983904025028

numpy聚合运算可以用面向对象的方式调用

In [9]:
big_array.min()

2.762554560664654e-07

In [10]:
big_array.max()

0.9999983904025028

In [11]:
big_array.sum()

500078.1537686462

### 多维度聚合

In [12]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
np.sum(X) #默认对所有元素聚合

120

In [11]:
np.sum(X, axis=0) #对一列聚合 

array([24, 28, 32, 36])

为什么axis=0是一列的和？沿着“行”的方向进行运算！

In [12]:
np.sum(X, axis=1) 

array([ 6, 22, 38, 54])

注意：axis描述的是将要被压缩的维度。

### 其他聚合操作

In [13]:
np.prod(X) #所有元素的积

0

In [14]:
np.prod(X + 1) # python天然支持大数运算 不用担心整型溢出

20922789888000

In [15]:
np.mean(X) 

7.5

In [16]:
np.median(X)

7.5

mean对 和样本整体差距非常大的点 非常敏感

In [17]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2000000000000002

In [18]:
np.median(v) #此时显然中值更能反映整体

2.0

In [15]:
np.percentile(big_array, q=50) #百分位 处于50%位置的数 和中位数是一个数

0.49996724646889146

In [16]:
np.median(big_array)

0.49996724646889146

In [17]:
np.percentile(big_array, q=100)

0.9999983904025028

In [18]:
np.max(big_array)

0.9999983904025028

In [19]:
for percent in [0, 25, 50, 75, 100]: #常用百分位 可以估计一个数据集的情况
    print(np.percentile(big_array, q=percent))

2.762554560664654e-07
0.25003297850728223
0.49996724646889146
0.7503934121969371
0.9999983904025028


In [24]:
np.var(big_array) #方差 variance

0.08335253444427035

In [25]:
np.std(big_array) #标准差 Standard Deviation

0.28870838997900694

In [21]:
x = np.random.normal(0, 1, size=1000000)

In [22]:
np.mean(x)

0.00019121511844767932

In [23]:
np.std(x)

1.000150476607936