# 创建numpy.array

In [1]:
import numpy as np

### numpy.array

In [2]:
nparr=np.array([i for i in range(10)]) #只需要传一个参数 列表初始化
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 其他创建numpy.array的方法

**zeros**

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

默认是浮点型

In [4]:
np.zeros(10).dtype

dtype('float64')

In [5]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

**ones**

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**full**

In [10]:
np.full((3,5),666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

Python中，当显式地写出参数名的时候，参数位置可以改变

In [11]:
np.full(fill_value=666.0, shape=(3,5))

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

**arange**

In [12]:
[i for i in range(0,20,2)] # [始，终)，步长

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [13]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
[i for i in range(0, 1, 0.2)] #Python range不能传入浮点数

TypeError: 'float' object cannot be interpreted as an integer

In [15]:
np.arange(0,1,0.2) #arange可以传入浮点数

array([0. , 0.2, 0.4, 0.6, 0.8])

In [16]:
np.arange(0,10) #默认步长为1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(10) #起始点默认从0开始

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**linspace**

In [18]:
np.linspace(0,20,10) #[0,20]区间等长地取出10个点（包括0和20这两个点）

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [19]:
np.linspace(0,20,11) #以2为步长要取11个点

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

**random**

*randint*

In [20]:
np.random.randint(0,10) #生成1个[0,10)区间的随机数

6

In [21]:
np.random.randint(0, 10, 10) #生成10个[0,10)区间的随机数

array([9, 5, 7, 6, 4, 9, 4, 2, 2, 4])

In [22]:
np.random.randint(0, 1, 10) #不包括右端点哦

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.random.randint(4, 8, size=(3,5))

array([[6, 7, 7, 7, 4],
       [7, 6, 4, 7, 6],
       [4, 6, 6, 7, 7]])

In [24]:
np.random.randint(4, 8, size=(3,5))

array([[5, 7, 5, 5, 6],
       [7, 6, 4, 6, 7],
       [4, 4, 4, 6, 7]])

*seed*

In [25]:
np.random.seed(666)

In [26]:
np.random.randint(4, 8, size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [27]:
np.random.randint(4, 8, size=(3,5))

array([[4, 6, 5, 7, 4],
       [6, 4, 7, 5, 6],
       [4, 7, 5, 5, 5]])

In [28]:
np.random.seed(666)
np.random.randint(4, 8, size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

设定相同的随机种子后生成的随机数是相同的，用于调试随机代码

*random*

生成浮点数

In [29]:
np.random.random() #生成1个[0,1)之间的随机数

0.2811684913927954

In [30]:
np.random.random(10) #生成一个大小为10且每个元素都在[0,1)之间的随机向量

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [31]:
np.random.random((3,5)) # 3*5 每个元素在[0,1)之间 随机矩阵

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949],
       [0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981]])

*normal*

In [32]:
np.random.normal() #生成一个符合正态分布(均值为0方差为1)的随机数

0.7760516793129695

In [33]:
np.random.normal(10, 100) #均值为10方差为100的随机数

128.06359754812632

In [34]:
np.random.normal(0, 1, (3,5)) #均值为0方差为1的3*5随机矩阵

array([[ 0.06102404,  1.07856138, -0.79783572,  1.1701326 ,  0.1121217 ],
       [ 0.03185388, -0.19206285,  0.78611284, -1.69046314, -0.98873907],
       [ 0.31398563,  0.39638567,  0.57656584, -0.07019407,  0.91250436]])

In [35]:
np.random.normal?

In [36]:
np.random?

In [37]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap